baseURL = "https://www.christopherfujino.com"
languageCode = "en-us"
title = "Teach Me To Code"
# https://gohugo.io/getting-started/configuration/#enablegitinfo
enableGitInfo = true

[params]
  homeText = "You just made a Hugo blog from scratch."
  repo = "https://github.com/christopherfujino/teach-me-to-code"
  gitMainBranch = "master"

[permalinks]
  blog = "/:filename/"

[taxonomies]
  tag = 'tags'

[menu]
  # layouts/partials/nav.html iterates over .Site.Menus.main
  # https://gohugo.io/content-management/menus/#properties-site-configuration
  [[menu.main]]
    name = "Tags"
    pageRef = "/tags"
    weight = 2
  [[menu.main]]
    name = "Résumé"
    pageRef = "/resume"
    weight = 3
  [[menu.main]]
    name = "Recommendations"
    pageRef = "/recommendations"
    weight = 4
  [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 5

# https://gohugo.io/getting-started/configuration-markup/#highlight
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    # https://xyproto.github.io/splash/docs/longer/all.html
    style = 'algol_nu'
    tabWidth = 2
  # https://gohugo.io/getting-started/configuration-markup/
  [markup.goldmark.renderer]
    unsafe = true

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = '../third_party/mononoki/export/'
    target = 'assets'
