baseURL = "http://example.org/"
languageCode = "en-us"
title = "Teach Me To Code"

[params]
  homeText = "You just made a Hugo blog from scratch."

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
