baseURL = "http://example.org/"
languageCode = "en-us"
title = "Teach Me To Code"

[params]
  homeText = "You just made a Hugo blog from scratch."

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 2
  [[menu.main]]
    name = "Résumé"
    url = "/resume"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

# https://gohugo.io/getting-started/configuration-markup/#highlight
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    # https://xyproto.github.io/splash/docs/longer/all.html
    style = 'algol_nu'
    tabWidth = 2
  # https://gohugo.io/getting-started/configuration-markup/
  [markup.goldmark.renderer]
    unsafe = true
