baseURL = "http://example.org/"
languageCode = "en-us"
title = "Teach Me To Code"

[params]
  homeText = "You just made a Hugo blog from scratch."

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
