name: Hugo-Build

on: push

jobs:
  # Set the job key. The key is displayed as the job name when a job name is
  # not provided
  build-hugo:
    # Name the job
    name: Build static site with Hugo
    # Set the docker image
    runs-on: ubuntu-latest

    steps:
      # Check out repo
      - name: Check out repo
        uses: actions/checkout@v2

      # TODO set up our own action in this repo
      - name: Build production site
        # https://github.com/klakegg/actions-hugo
        uses: klakegg/actions-hugo@1.0.0
        with:
          # https://hub.docker.com/r/klakegg/hugo/tags
          version: 0.75.1
          image: debian
          # Path to hugo project root
          source: blog/
          env: production

      - name: Push to teach-me-to-code.github.io
        uses: appleboy/gh-pages-action@v0.0.2
        # https://github.com/appleboy/gh-pages-action/blob/master/action.yml
        with:
          # Secrets should be configured in GitHub as a repo setting
          username: ${{ secrets.USERNAME }}
          # Should be a personal access token
          password: ${{ secrets.PASSWORD }}
          remote_url: https://github.com/teach-me-to-code/teach-me-to-code.github.io
          commit_author: coder_bot
          commit_author_email: github-action@users.noreply.github.com
          target_branch: master
          # Directory of content to sync
          target_directory: ./
          # Directory of content to publish
          pages_directory: blog/public/
