name: Hugo-Build

on: push

jobs:
  # Set the job key. The key is displayed as the job name when a job name is
  # not provided
  build-hugo:
    # Name the job
    name: Build static site with Hugo
    # Set the docker image
    runs-on: ubuntu-latest

    steps:
      # Check out repo
      - name: Check out repo
        uses: actions/checkout@v2

      # TODO set up our own action in this repo
      - name: For now, super-lint
        uses: klakegg/actions-hugo@1.0.0
        with:
          version: 0.76.0
          source: blog/
          env: production
